# Generated by Django 6.1 on 2026-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_link',
            field=models.URLField(blank=True),
        ),
    ]
